# Generated by Django 2.1 on 2011-04-12 23:47

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('duration', models.CharField(max_length=10)),
                ('bodysnippet', models.TextField(blank=True, default='', null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('vid', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('status', models.CharField(choices=[('', '---------'), ('draft', 'Draft'), ('published', 'Published')], max_length=10)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('', '---------'), ('Agriculture & Food', 'Agriculture & Food'), ('Animals & Pets', 'Animals & Pets'), ('Babies & Kids', 'Babies & Kids'), ('Commercial Equipment & Tool', 'Commercial Equipment & Tool'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Health & Beauty', 'Health & Beauty'), ('Home, Furniture & Appliances', 'Home, Furniture & Appliances'), ('Mobile Phones & Tablets', 'Mobile Phones & Tablets'), ('Property', 'Property'), ('Repair & Construction', 'Repair & Construction'), ('Seeking Work - CVs', 'Seeking Work - CVs'), ('Services', 'Services'), ('Sport, Art & Outdoors', 'Sport, Art & Outdoors'), ('Vehicles', 'Vehicles')], max_length=100)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('bodysnippet', models.TextField(blank=True, default='', null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('link1', models.TextField(blank=True, default='', null=True)),
                ('video2', models.FileField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('body1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('link2', models.TextField(blank=True, default='', null=True)),
                ('video3', models.FileField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('body2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('link3', models.TextField(blank=True, default='', null=True)),
                ('video4', models.FileField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('body3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('link4', models.TextField(blank=True, default='', null=True)),
                ('video5', models.FileField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('body4', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('link5', models.TextField(blank=True, default='', null=True)),
                ('video6', models.FileField(blank=True, null=True, upload_to='')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='')),
                ('body5', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('link6', models.TextField(blank=True, default='', null=True)),
                ('video7', models.FileField(blank=True, null=True, upload_to='')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='')),
                ('body6', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('link7', models.TextField(blank=True, default='', null=True)),
                ('video8', models.FileField(blank=True, null=True, upload_to='')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='')),
                ('body7', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('link8', models.TextField(blank=True, default='', null=True)),
                ('video9', models.FileField(blank=True, null=True, upload_to='')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='')),
                ('body8', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('link9', models.TextField(blank=True, default='', null=True)),
                ('video10', models.FileField(blank=True, null=True, upload_to='')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='')),
                ('body9', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('link10', models.TextField(blank=True, default='', null=True)),
                ('video11', models.FileField(blank=True, null=True, upload_to='')),
                ('image11', models.ImageField(blank=True, null=True, upload_to='')),
                ('body10', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('link11', models.TextField(blank=True, default='', null=True)),
                ('video12', models.FileField(blank=True, null=True, upload_to='')),
                ('image12', models.ImageField(blank=True, null=True, upload_to='')),
                ('link12', models.TextField(blank=True, default='', null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(choices=[('', '---------'), ('7', ' 1 Week'), ('14', '2 Weeks'), ('28', '3 Weeks'), ('31', '1 Month'), ('366', '1 Year')], default=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('restrict_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('favourite', models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=160)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ent.Article')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ent.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ent.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_reference_number', models.CharField(max_length=200)),
            ],
        ),
    ]
